name: Docker Image CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the ToolApplicaiton Docker image
      run: docker build . --file Dockerfile --tag toolframework/toolapplication:latest
    - name: Build the ToolFrameworkApplication Docker image
      run: docker build . --file Dockerfile.ToolFramework --tag toolframework/toolframeworkapp:latest
    - name: Build the ToolDAQApplication Docker image
      run: docker build . --file Dockerfile.ToolDAQ --tag tooldaq/tooldaqapp:latest    
   
    - name: docker login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: push docker images
      run: docker push toolframework/toolapplication:latest 
       && docker push toolframework/toolframeworkapp:latest
       && docker push tooldaq/tooldaqapp:latest
